# Generated by Django 4.2.1 on 2023-05-31 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssurerMalade',
            fields=[
                ('matricule', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('lieuAdress', models.CharField(max_length=255)),
                ('telephone', models.IntegerField()),
                ('assuerMdp', models.CharField(max_length=255)),
                ('statusAjour', models.BooleanField()),
                ('dateDebutDroit', models.DateField()),
                ('dateFinDroit', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pathologie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomPathologie', models.CharField(blank=True, choices=[('c1', 'c1'), ('c2', 'c2'), ('c3', 'c3'), ('c4', 'c4'), ('c5', 'c5'), ('c6', 'c6'), ('c7', 'c7'), ('c8', 'c8'), ('c9', 'c9'), ('c10', 'c10'), ('c11', 'c11'), ('c12', 'c12'), ('c13', 'c13'), ('c14', 'c14'), ('c15', 'c15'), ('c16', 'c16'), ('c17', 'c17'), ('c18', 'c18'), ('c19', 'c19'), ('c20', 'c20'), ('c21', 'c21'), ('c22', 'c22'), ('c23', 'c23'), ('c24', 'c24'), ('c25', 'c25'), ('c26', 'c26'), ('c27', 'c27')], max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssurerMalade100',
            fields=[
                ('assurermalade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.assurermalade')),
            ],
            options={
                'verbose_name_plural': 'Assurer malade 100%',
            },
            bases=('app.assurermalade',),
        ),
        migrations.CreateModel(
            name='AssurerMalade80',
            fields=[
                ('assurermalade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.assurermalade')),
            ],
            options={
                'verbose_name_plural': 'Assurer malade 80%',
            },
            bases=('app.assurermalade',),
        ),
        migrations.CreateModel(
            name='AssurerMaladePathologieAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assurer_malade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathologie_associations', to='app.assurermalade')),
                ('pathologie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pathologie')),
            ],
            options={
                'verbose_name_plural': 'Assurer Malade - Pathologie Associations',
            },
        ),
    ]
