# Generated by Django 4.2.1 on 2023-06-04 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_pathologie_nompathologie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('CodeMedicament', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='Code Médicament')),
                ('nomMedicament', models.CharField(max_length=255, verbose_name='Nom Médicament')),
                ('forme', models.CharField(choices=[('comprimé', 'Comprimé'), ('capsule', 'Capsule'), ('sirop', 'Sirop'), ('suspension', 'Suspension'), ('gelule', 'Gélule'), ('patch', 'Patch'), ('suppositoire', 'Suppositoire'), ('inhalateur', 'Inhalateur')], max_length=255, verbose_name='Forme')),
                ('dosage', models.CharField(max_length=255, verbose_name='Dosage')),
                ('Conditionnement', models.CharField(max_length=255, verbose_name='Conditionnement')),
                ('prixPublic', models.DecimalField(decimal_places=6, max_digits=9999, verbose_name='Prix Public')),
                ('tarifReference', models.DecimalField(decimal_places=6, max_digits=9999, verbose_name='Tarif de Référence')),
            ],
        ),
        migrations.CreateModel(
            name='Consommation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité')),
                ('total_tarif_reference', models.DecimalField(decimal_places=6, max_digits=9999, verbose_name='Total Tarif de Référence')),
                ('total_prix_public', models.DecimalField(decimal_places=6, max_digits=9999, verbose_name='Total Prix Public')),
                ('assurer_malade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consommations', to='app.assurermalade')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.medicament', verbose_name='Médicament')),
            ],
        ),
    ]
